# Site
name: 'Machine Learning Community'
description: 'A vibrant community for machine learning enthusiasts to share knowledge, resources, and stay updated with the latest advancements in the machine learning domain.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'mlcommunity'
email: 'mlblogspk@gmail.com'
mailchimp-list: 'https://mlcommunity.list-manage.com/subscribe/post?u=1234567890abcdef123456789&id=abcdef123456'

include: ["_pages"]
permalink: /:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  
authors:
  admin:
    name:           ML Community Admin
    site:           https://www.mlcommunity.org
    avatar:         /assets/images/avatar1.jpg
    bio:            "Administrator for the Machine Learning Community, passionate about fostering collaboration and innovation in ML."
    email:          mlblogspk@gmail.com
    twitter:        https://twitter.com/mlcommunityorg
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: admin
      avatar: /assets/images/admin_avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
